version: '3'

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saLvador7
      POSTGRES_DB: practica
    container_name: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: salvav/mi-backend:latest
    container_name: backend_ejemplo
    build: .
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - db
    
  frontend:
    container_name: frontend_ejemplo
    image: salvav/mi-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

